/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_LIBRARY_H
#define _MOCK_LIBRARY_H

#include "library.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_library_Init(void);
void mock_library_Destroy(void);
void mock_library_Verify(void);




#define library_func_Ignore() library_func_CMockIgnore()
void library_func_CMockIgnore(void);
#define library_func_Expect(a) library_func_CMockExpect(__LINE__, a)
void library_func_CMockExpect(UNITY_LINE_TYPE cmock_line, int a);
typedef void (* CMOCK_library_func_CALLBACK)(int a, int cmock_num_calls);
void library_func_StubWithCallback(CMOCK_library_func_CALLBACK Callback);
#define library_func_IgnoreArg_a() library_func_CMockIgnoreArg_a(__LINE__)
void library_func_CMockIgnoreArg_a(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
