/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "mock_library.h"

static const char* CMockString_a = "a";
static const char* CMockString_library_func = "library_func";

typedef struct _CMOCK_library_func_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  int Expected_a;
  int IgnoreArg_a;

} CMOCK_library_func_CALL_INSTANCE;

static struct mock_libraryInstance
{
  int library_func_IgnoreBool;
  CMOCK_library_func_CALLBACK library_func_CallbackFunctionPointer;
  int library_func_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE library_func_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_library_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.library_func_IgnoreBool)
    Mock.library_func_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_library_func);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.library_func_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.library_func_CallbackFunctionPointer != NULL)
    Mock.library_func_CallInstance = CMOCK_GUTS_NONE;
}

void mock_library_Init(void)
{
  mock_library_Destroy();
}

void mock_library_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.library_func_CallbackFunctionPointer = NULL;
  Mock.library_func_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void library_func(int a)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_library_func_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_library_func);
  cmock_call_instance = (CMOCK_library_func_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.library_func_CallInstance);
  Mock.library_func_CallInstance = CMock_Guts_MemNext(Mock.library_func_CallInstance);
  if (Mock.library_func_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.library_func_CallbackFunctionPointer != NULL)
  {
    Mock.library_func_CallbackFunctionPointer(a, Mock.library_func_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_a)
  {
    UNITY_SET_DETAILS(CMockString_library_func,CMockString_a);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_a, a, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_library_func(CMOCK_library_func_CALL_INSTANCE* cmock_call_instance, int a)
{
  cmock_call_instance->Expected_a = a;
  cmock_call_instance->IgnoreArg_a = 0;
}

void library_func_CMockIgnore(void)
{
  Mock.library_func_IgnoreBool = (int)1;
}

void library_func_CMockExpect(UNITY_LINE_TYPE cmock_line, int a)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_library_func_CALL_INSTANCE));
  CMOCK_library_func_CALL_INSTANCE* cmock_call_instance = (CMOCK_library_func_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.library_func_CallInstance = CMock_Guts_MemChain(Mock.library_func_CallInstance, cmock_guts_index);
  Mock.library_func_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_library_func(cmock_call_instance, a);
  UNITY_CLR_DETAILS();
}

void library_func_StubWithCallback(CMOCK_library_func_CALLBACK Callback)
{
  Mock.library_func_IgnoreBool = (int)0;
  Mock.library_func_CallbackFunctionPointer = Callback;
}

void library_func_CMockIgnoreArg_a(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_library_func_CALL_INSTANCE* cmock_call_instance = (CMOCK_library_func_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.library_func_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_a = 1;
}

